import fs from "node:fs";
import path from "node:path";

import type Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

import * as schema from "@/lib/db/schema";

/**
 * Applies SQL migrations under ./drizzle (generated by drizzle-kit).
 */
export function runMigrations(db: Database.Database): void {
  const migrationsFolder = path.join(process.cwd(), "drizzle");
  if (!fs.existsSync(migrationsFolder)) {
    throw new Error(
      `Missing Drizzle migrations folder at ${migrationsFolder}. Run pnpm db:generate after schema changes.`,
    );
  }
  const drizzleDb = drizzle(db, { schema });
  migrate(drizzleDb, { migrationsFolder });
}
